development:
  cloud_name: dkprc38da
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_KEY_CLOUDINARY']
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dkprc38da
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_KEY_CLOUDINARY']
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dkprc38da
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_KEY_CLOUDINARY']
  enhance_image_tag: true
  static_image_support: false

  
